version: '3'

services:
  docker-mongodb:
    image: mongo:latest
    environment:
      ADVERTISED_HOST: 127.0.0.1
      ADVERTISED_PORT: 27017
    ports:
      - "27017:27017"
    networks:
      - shared-net  
  docker-car-data:
    image: car2godeveloper/api-for-coding-challenge:latest
    ports:
      - "3000:3000"
    networks:
      - shared-net  
  docker-car:
    image: car
    depends_on:
      - docker-mongodb
      - docker-car-data
    ports:
      - 8000:8080
    environment:
      spring.profiles.active: docker
    networks:
      - shared-net  
volumes:
  my-datavolume: {}
networks:
  shared-net:
    driver: bridge  

